spring.application.name=ai-code-reviewer
server.port=8080
github.token=${GITHUB_TOKEN}
openai.api.key=${OPENAI_API_KEY}

#spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

github.webhook.secret=${GITHUB_WEBHOOK_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jaashi117@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

notification.email.to=jaashi117@gmail.com